### PR TITLE
hdfSuites

### PR DESCRIPTION
**Pull request by scgordon**
issues running locally. If on works they all do. Please test one
against a record (any dialect) and integrate into HDF build of Engine

### CODE REVIEW

**Comment by mbjones** [comment]
@gothub and @amoeba Could you help @scgordon with this and merge when the build errors are gone?

**Comment by gothub** [comment]
I'll look into this - @amoeba I inadvertently hit the review button for you, please ignore.

**Comment by amoeba** [comment]
The build failures are unrelated to this PR so merge away.

**Comment by scgordon** [comment]
I got it running locally thanks to your suggestion. I can see some cleanup I have to do before merging

**Pull request merged**
