### PR TITLE
removeSpacesPyVariables

### PR DESCRIPTION
**Pull request by scgordon**
removed spaces from itemNames in Python code.

### CODE REVIEW

**Comment by leinfelder** [comment]
This overwrote my changes to make it schema valid.

You can skipthe build and just generate the schema using:
`mvn generate-resources`

**Comment by scgordon** [comment]
generated schema, getting one error repeated for each check saying:

Invalid content was found starting with element 'type'. One of '{dialect}' is expected.

Which is strange because 'dialect' was the element immediately preceding 'type'.

**Comment by leinfelder** [comment]
The element sequence in a check needs to be in the correct order as defined in the schema:
"id", "name", "description", "type", "level", "environment", "code", "library", "inheritState", "selector", "dialect"

**Comment by leinfelder** [comment]
`<xs:complexType name="check">
    <xs:sequence>
      <xs:element name="id" type="xs:string"/>
      <xs:element name="name" type="xs:string" minOccurs="0"/>
      <xs:element name="description" type="xs:string" minOccurs="0"/>
      <xs:element name="type" type="xs:string" minOccurs="0"/>
      <xs:element name="level" type="tns:level" minOccurs="0"/>
      <xs:element name="environment" type="xs:string" minOccurs="0"/>
      <xs:element name="code" type="xs:string" minOccurs="0"/>
      <xs:element name="library" type="xs:anyURI" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="inheritState" type="xs:boolean" minOccurs="0"/>
      <xs:element name="selector" type="tns:selector" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="dialect" type="tns:dialect" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>`

**Comment by scgordon** [comment]
Interesting, no problems shifting the elements into their new order. Will have it updated tomorrow. Do you have definitions/uses for the new (to me at least) elements documented? (eg InheritState, library,...)

**Comment by leinfelder** [comment]
Will write it up soon!

**Comment by leinfelder** [comment]
I've added java doc comments to the model classes and these will flow into schema once I resolve a maven plugin issue with the devs of that jaxb plugin. https://github.com/NCEAS/mdqengine/tree/master/src/main/java/edu/ucsb/nceas/mdqengine/model
Is this enough of a start to help?

**Comment by scgordon** [comment]
Yep, that's helpful, thanks!

**Pull request merged**
